apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: db
  labels:
    app: mysql
spec:
  containers:
    - name: mysql
      image: 226220391179.dkr.ecr.us-east-1.amazonaws.com/mysql:v0.1
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: yourpassword
      ports:
        - containerPort: 3306
