apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: app
  labels:
    app: webapp
spec:
  selector:
    app: employees
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort
  