apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: app
  labels:
    app: employees
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
        - name: webapp-container
          image: 226220391179.dkr.ecr.us-east-1.amazonaws.com/webapp:v0.1
          ports:
            - containerPort: 80
          env:
            - name: DBHOST
              value: "mysql.db.svc.cluster.local"
            - name: DBPORT
              value: "3306"
            - name: DBUSER
              value: "root"
            - name: DBPWD
              value: "yourpassword"
            - name: DATABASE
              value: "employees"
            - name: APP_COLOR
              value: "blue"